1450167602525	Sync.LogManager	DEBUG	Flushing file log
1450167602525	Sync.LogManager	TRACE	Beginning stream copy to error-sync-1450167602524.txt: 1450167602525
1450167602527	Sync.Service	DEBUG	Exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1307 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < _lockedSync()@resource://gre/modules/services-sync/service.js:1294 < sync/<()@resource://gre/modules/services-sync/service.js:1286 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1274 < <file:unknown>
1450167602536	Sync.SyncScheduler	DEBUG	Global Score threshold hit, triggering sync.
1450167602637	Sync.Engine.History	WARN	Failed to reconcile incoming record 3x-UZB0C2-Dj
1450167602638	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602639	Sync.Engine.History	WARN	Failed to reconcile incoming record SvOMrNwosImU
1450167602639	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602640	Sync.Engine.History	WARN	Failed to reconcile incoming record S4Xk163zWRIy
1450167602641	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602642	Sync.Engine.History	WARN	Failed to reconcile incoming record GMAl8j4agd2G
1450167602642	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602643	Sync.Engine.History	WARN	Failed to reconcile incoming record ZeZbczBTMeyr
1450167602644	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602645	Sync.Engine.History	WARN	Failed to reconcile incoming record yOOC_7OjEXaG
1450167602645	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602646	Sync.Engine.History	WARN	Failed to reconcile incoming record yhCZvVSEokSS
1450167602647	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602648	Sync.Engine.History	WARN	Failed to reconcile incoming record yBghQuzOR50q
1450167602648	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602649	Sync.Engine.History	WARN	Failed to reconcile incoming record XxLkmPmiDd6w
1450167602650	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602652	Sync.Engine.History	WARN	Failed to reconcile incoming record xO3dLddedL7u
1450167602652	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602653	Sync.Engine.History	WARN	Failed to reconcile incoming record WzxwjYSpQenI
1450167602654	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602655	Sync.Engine.History	WARN	Failed to reconcile incoming record WIR3SCEj1Sqm
1450167602655	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602656	Sync.Engine.History	WARN	Failed to reconcile incoming record v9h_b3Q75Akw
1450167602657	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602658	Sync.Engine.History	WARN	Failed to reconcile incoming record uWh-L6iGtpki
1450167602658	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602659	Sync.Engine.History	WARN	Failed to reconcile incoming record UOUA0cE5dL71
1450167602660	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602661	Sync.Engine.History	WARN	Failed to reconcile incoming record uoJsyc-bqsSi
1450167602661	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602662	Sync.Engine.History	WARN	Failed to reconcile incoming record Tnlk_rd5eOWH
1450167602663	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602663	Sync.Engine.History	WARN	Failed to reconcile incoming record t3_6VXySQmqU
1450167602664	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602665	Sync.Engine.History	WARN	Failed to reconcile incoming record SDbFNoV4uXpC
1450167602665	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602666	Sync.Engine.History	WARN	Failed to reconcile incoming record rx71TFZ-FWyy
1450167602667	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602668	Sync.Engine.History	WARN	Failed to reconcile incoming record Rq9k9uDE-wBn
1450167602668	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602669	Sync.Engine.History	WARN	Failed to reconcile incoming record RMA77v_-_YYW
1450167602670	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602671	Sync.Engine.History	WARN	Failed to reconcile incoming record RBi9oQ4vYv6f
1450167602671	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602672	Sync.Engine.History	WARN	Failed to reconcile incoming record QZ3etegxm6O3
1450167602673	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602673	Sync.Engine.History	WARN	Failed to reconcile incoming record QocpfWmcg3xs
1450167602674	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602675	Sync.Engine.History	WARN	Failed to reconcile incoming record pc-YGWpc6ohB
1450167602676	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602676	Sync.Engine.History	WARN	Failed to reconcile incoming record p3nbt_F3p1E3
1450167602677	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602678	Sync.Engine.History	WARN	Failed to reconcile incoming record oSCjAzaCMYhW
1450167602679	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602679	Sync.Engine.History	WARN	Failed to reconcile incoming record ONb_XxJij15h
1450167602680	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602681	Sync.Engine.History	WARN	Failed to reconcile incoming record oerT5BTbZqBr
1450167602682	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602683	Sync.Engine.History	WARN	Failed to reconcile incoming record nJBbi_FFlt-e
1450167602683	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602684	Sync.Engine.History	WARN	Failed to reconcile incoming record MRLdRcDGWRMh
1450167602685	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602685	Sync.Engine.History	WARN	Failed to reconcile incoming record MCYsr23qQxvu
1450167602686	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602687	Sync.Engine.History	WARN	Failed to reconcile incoming record Lu96z38BPBdc
1450167602687	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602688	Sync.Engine.History	WARN	Failed to reconcile incoming record LI2VQSFwjwK5
1450167602689	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602689	Sync.Engine.History	WARN	Failed to reconcile incoming record LEJ8jo7sCUIv
1450167602690	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602691	Sync.Engine.History	WARN	Failed to reconcile incoming record l6CTko0bim9e
1450167602691	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602692	Sync.Engine.History	WARN	Failed to reconcile incoming record KzSvmCfUMayd
1450167602693	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602694	Sync.Engine.History	WARN	Failed to reconcile incoming record k2srAIUbfKYI
1450167602694	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602695	Sync.Engine.History	WARN	Failed to reconcile incoming record jNPlPo57v4zq
1450167602696	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602697	Sync.Engine.History	WARN	Failed to reconcile incoming record jkZPMAk2an2_
1450167602697	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602698	Sync.Engine.History	WARN	Failed to reconcile incoming record i_g9OicSicC4
1450167602699	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602699	Sync.Engine.History	WARN	Failed to reconcile incoming record ITbkqogMZh53
1450167602700	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602701	Sync.Engine.History	WARN	Failed to reconcile incoming record IBCjqMamBBkd
1450167602701	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602702	Sync.Engine.History	WARN	Failed to reconcile incoming record I4uMCPaVWKdZ
1450167602703	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602704	Sync.Engine.History	WARN	Failed to reconcile incoming record HMktdyYOSlau
1450167602705	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602706	Sync.Engine.History	WARN	Failed to reconcile incoming record GA6ZMGtOqisj
1450167602706	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602707	Sync.Engine.History	WARN	Failed to reconcile incoming record fIS_VnTJso8V
1450167602708	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602708	Sync.Engine.History	WARN	Failed to reconcile incoming record F3I8eIugVJU2
1450167602709	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602710	Sync.Engine.History	WARN	Failed to reconcile incoming record EMaQ4Hbz2rcK
1450167602710	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602711	Sync.Engine.History	WARN	Failed to reconcile incoming record dJN-ZubzWyx0
1450167602712	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602712	Sync.Engine.History	WARN	Failed to reconcile incoming record dha3nzMpwiIW
1450167602713	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602714	Sync.Engine.History	WARN	Failed to reconcile incoming record CfvqrOf81RY0
1450167602714	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602716	Sync.Engine.History	WARN	Failed to reconcile incoming record BDjEVtyKWYjX
1450167602716	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602717	Sync.Engine.History	WARN	Failed to reconcile incoming record AzvIBMrBN2si
1450167602718	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602718	Sync.Engine.History	WARN	Failed to reconcile incoming record aVbyHg25e1Ko
1450167602719	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602720	Sync.Engine.History	WARN	Failed to reconcile incoming record 8NI07DcECtxL
1450167602720	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602721	Sync.Engine.History	WARN	Failed to reconcile incoming record 8IOEmrG2md9z
1450167602722	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602723	Sync.Engine.History	WARN	Failed to reconcile incoming record 7xEw4MOoSdcl
1450167602723	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602724	Sync.Engine.History	WARN	Failed to reconcile incoming record 7SXx6uHZvwfk
1450167602725	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602726	Sync.Engine.History	WARN	Failed to reconcile incoming record 6XqNWJBnB-JW
1450167602726	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602727	Sync.Engine.History	WARN	Failed to reconcile incoming record 6xnudKbNiN-B
1450167602728	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602728	Sync.Engine.History	WARN	Failed to reconcile incoming record 6rGsxduCo9z4
1450167602729	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602730	Sync.Engine.History	WARN	Failed to reconcile incoming record 56GFw-vNkOu1
1450167602731	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602731	Sync.Engine.History	WARN	Failed to reconcile incoming record 4rNpKr0GFuqV
1450167602732	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602733	Sync.Engine.History	WARN	Failed to reconcile incoming record 4IL__k7rWgsb
1450167602733	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602734	Sync.Engine.History	WARN	Failed to reconcile incoming record 3uWG-QXJQ6_-
1450167602735	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602736	Sync.Engine.History	WARN	Failed to reconcile incoming record 0H2rCCfPRUdm
1450167602736	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602737	Sync.Engine.History	WARN	Failed to reconcile incoming record 0f-RkjEkCL6f
1450167602738	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602739	Sync.Engine.History	WARN	Failed to reconcile incoming record -12LJL3MPJMv
1450167602739	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602740	Sync.Engine.History	WARN	Failed to reconcile incoming record XudUThlhLaQi
1450167602741	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602742	Sync.Engine.History	WARN	Failed to reconcile incoming record nZYfg_qdNdZ6
1450167602742	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602743	Sync.Engine.History	WARN	Failed to reconcile incoming record mgjYQw6ror2V
1450167602744	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602745	Sync.Engine.History	WARN	Failed to reconcile incoming record F_XEBrMcIRFM
1450167602746	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602747	Sync.Engine.History	WARN	Failed to reconcile incoming record BUcFXMhbAt1k
1450167602748	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602749	Sync.Engine.History	WARN	Failed to reconcile incoming record aulOr4BWJdi8
1450167602749	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602750	Sync.Engine.History	WARN	Failed to reconcile incoming record 9X1hZGw29b-q
1450167602751	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602753	Sync.Engine.History	WARN	Failed to reconcile incoming record 94jb1H1U4ZUz
1450167602753	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602754	Sync.Engine.History	WARN	Failed to reconcile incoming record 8Gy-Bn3FIjZR
1450167602755	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602756	Sync.Engine.History	WARN	Failed to reconcile incoming record _2A9TBSBysXU
1450167602756	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602758	Sync.Engine.History	WARN	Failed to reconcile incoming record p0GDjteRJrzw
1450167602758	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602759	Sync.Engine.History	WARN	Failed to reconcile incoming record mQUIvBLIew2E
1450167602760	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602761	Sync.Engine.History	WARN	Failed to reconcile incoming record kF3rR_Gwrpu1
1450167602761	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602762	Sync.Engine.History	WARN	Failed to reconcile incoming record Jv5KPV-XTOy2
1450167602763	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602764	Sync.Engine.History	WARN	Failed to reconcile incoming record Ds6dDiP4_9t8
1450167602765	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602766	Sync.Engine.History	WARN	Failed to reconcile incoming record 9rn5isbhroCN
1450167602766	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602767	Sync.Engine.History	WARN	Failed to reconcile incoming record YbMHbPYprDSU
1450167602768	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602769	Sync.Engine.History	WARN	Failed to reconcile incoming record HZSVxWSRX1re
1450167602769	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602770	Sync.Engine.History	WARN	Failed to reconcile incoming record F-oL50XQUlJ4
1450167602771	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602772	Sync.Engine.History	WARN	Failed to reconcile incoming record 68PTJ6iqRxHb
1450167602772	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602776	Sync.Engine.History	WARN	Failed to reconcile incoming record xnbqxGuLXTVf
1450167602776	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602778	Sync.Engine.History	WARN	Failed to reconcile incoming record q5oKdQymDo8W
1450167602778	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602779	Sync.Engine.History	WARN	Failed to reconcile incoming record PVtGmyZyNiR2
1450167602780	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602781	Sync.Engine.History	WARN	Failed to reconcile incoming record nhYY8vcmicSQ
1450167602781	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602782	Sync.Engine.History	WARN	Failed to reconcile incoming record ICH6Ytp5Kb3A
1450167602783	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602784	Sync.Engine.History	WARN	Failed to reconcile incoming record EYN1rt_XlWdW
1450167602784	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602785	Sync.Engine.History	WARN	Failed to reconcile incoming record aucvBSsJicV2
1450167602786	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602787	Sync.Engine.History	WARN	Failed to reconcile incoming record WyJ4YiSycCHR
1450167602787	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602788	Sync.Engine.History	WARN	Failed to reconcile incoming record TbXJVG81WtJ2
1450167602789	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602790	Sync.Engine.History	WARN	Failed to reconcile incoming record RqbU1zHW9fRX
1450167602790	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602791	Sync.Engine.History	WARN	Failed to reconcile incoming record pdu-y0JI_mFs
1450167602792	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602793	Sync.Engine.History	WARN	Failed to reconcile incoming record CTeELJwRNl-0
1450167602793	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602794	Sync.Engine.History	WARN	Failed to reconcile incoming record BmYrywt2xGt6
1450167602795	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602796	Sync.Engine.History	WARN	Failed to reconcile incoming record 71s-w6kJnhCb
1450167602796	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602797	Sync.Engine.History	WARN	Failed to reconcile incoming record HZ5MWp9VR30q
1450167602798	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602799	Sync.Engine.History	WARN	Failed to reconcile incoming record vLn1ae59zWIu
1450167602800	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602801	Sync.Engine.History	WARN	Failed to reconcile incoming record Ga7xkatuQlRr
1450167602802	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602803	Sync.Engine.History	WARN	Failed to reconcile incoming record vioGm5ewRP7H
1450167602803	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602804	Sync.Engine.History	WARN	Failed to reconcile incoming record U8yGjxtefqH4
1450167602805	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602806	Sync.Engine.History	WARN	Failed to reconcile incoming record jddAun1s71a0
1450167602806	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602807	Sync.Engine.History	WARN	Failed to reconcile incoming record Wl7C6zYJtqdS
1450167602807	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602808	Sync.Engine.History	WARN	Failed to reconcile incoming record tGqbdb0CJtjf
1450167602809	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602810	Sync.Engine.History	WARN	Failed to reconcile incoming record sIT1f0EZoqKJ
1450167602810	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602811	Sync.Engine.History	WARN	Failed to reconcile incoming record rPKblIR2dunz
1450167602812	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602813	Sync.Engine.History	WARN	Failed to reconcile incoming record OwgD1REAu_JB
1450167602813	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602814	Sync.Engine.History	WARN	Failed to reconcile incoming record kn3iWLyF9smP
1450167602815	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602816	Sync.Engine.History	WARN	Failed to reconcile incoming record KKO0psqp2_9f
1450167602816	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602817	Sync.Engine.History	WARN	Failed to reconcile incoming record Hy-uan1fKJH9
1450167602818	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602819	Sync.Engine.History	WARN	Failed to reconcile incoming record FIZA1JMqNTWz
1450167602819	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602820	Sync.Engine.History	WARN	Failed to reconcile incoming record bsDY5RMQolbn
1450167602821	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602822	Sync.Engine.History	WARN	Failed to reconcile incoming record 99mvjRp_6wuo
1450167602822	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602823	Sync.Engine.History	WARN	Failed to reconcile incoming record 7-Q0d1FKirOz
1450167602824	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602825	Sync.Engine.History	WARN	Failed to reconcile incoming record ZdNCkC1NbPpU
1450167602825	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602826	Sync.Engine.History	WARN	Failed to reconcile incoming record wPViSESi_wnr
1450167602827	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602827	Sync.Engine.History	WARN	Failed to reconcile incoming record TK-Ue2_4Iqzw
1450167602828	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602829	Sync.Engine.History	WARN	Failed to reconcile incoming record PhQFAEQMuJu0
1450167602830	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602830	Sync.Engine.History	WARN	Failed to reconcile incoming record JVYj2-EAMnbj
1450167602831	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602832	Sync.Engine.History	WARN	Failed to reconcile incoming record HRDo29vONh-9
1450167602833	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602834	Sync.Engine.History	WARN	Failed to reconcile incoming record 42Fc8JhmjuB1
1450167602834	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602835	Sync.Engine.History	WARN	Failed to reconcile incoming record X0Zw23mz_76P
1450167602836	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602836	Sync.Engine.History	WARN	Failed to reconcile incoming record wIJg-jluUWyA
1450167602837	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602838	Sync.Engine.History	WARN	Failed to reconcile incoming record QLKpXjldkkxs
1450167602839	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602840	Sync.Engine.History	WARN	Failed to reconcile incoming record Q3eX41H4loyb
1450167602840	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602841	Sync.Engine.History	WARN	Failed to reconcile incoming record PNQeHf7nnJtu
1450167602842	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602843	Sync.Engine.History	WARN	Failed to reconcile incoming record I_fmpEr36IFO
1450167602843	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602844	Sync.Engine.History	WARN	Failed to reconcile incoming record Dvf50rMxwVCS
1450167602845	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602846	Sync.Engine.History	WARN	Failed to reconcile incoming record 7w7zzsHAbwr_
1450167602846	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602847	Sync.Engine.History	WARN	Failed to reconcile incoming record 6R748wo79U_Q
1450167602848	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602848	Sync.Engine.History	WARN	Failed to reconcile incoming record z1fPMDCTH64f
1450167602849	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602850	Sync.Engine.History	WARN	Failed to reconcile incoming record ycP1bbznwpk7
1450167602850	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602851	Sync.Engine.History	WARN	Failed to reconcile incoming record vGoizWYjvpaH
1450167602852	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602853	Sync.Engine.History	WARN	Failed to reconcile incoming record tdL2VsKdghOA
1450167602853	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602854	Sync.Engine.History	WARN	Failed to reconcile incoming record qVhA3oQWc_NS
1450167602855	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602856	Sync.Engine.History	WARN	Failed to reconcile incoming record dv8MfCqKj886
1450167602856	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602857	Sync.Engine.History	WARN	Failed to reconcile incoming record DAD4ewzdpktS
1450167602858	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602858	Sync.Engine.History	WARN	Failed to reconcile incoming record 43ScMYcJ-mqf
1450167602859	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602860	Sync.Engine.History	WARN	Failed to reconcile incoming record yPmjyajkqOYW
1450167602860	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602861	Sync.Engine.History	WARN	Failed to reconcile incoming record r3JddiVlmSjN
1450167602862	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602863	Sync.Engine.History	WARN	Failed to reconcile incoming record _zbMaPoNftvl
1450167602863	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602864	Sync.Engine.History	WARN	Failed to reconcile incoming record Z7JzRnCan5WZ
1450167602865	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602865	Sync.Engine.History	WARN	Failed to reconcile incoming record W4lPpQjToQyr
1450167602866	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602867	Sync.Engine.History	WARN	Failed to reconcile incoming record VvhRq5JGP-xo
1450167602867	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602868	Sync.Engine.History	WARN	Failed to reconcile incoming record vFgvfoetjpAw
1450167602869	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602870	Sync.Engine.History	WARN	Failed to reconcile incoming record npUGEhVnNH16
1450167602870	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602871	Sync.Engine.History	WARN	Failed to reconcile incoming record NpD7eVtdfDjt
1450167602872	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602873	Sync.Engine.History	WARN	Failed to reconcile incoming record Kk0KChwLo38q
1450167602873	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602874	Sync.Engine.History	WARN	Failed to reconcile incoming record KGJieMQiu-mQ
1450167602875	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602875	Sync.Engine.History	WARN	Failed to reconcile incoming record Ibi9NSw2KIh-
1450167602876	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602877	Sync.Engine.History	WARN	Failed to reconcile incoming record hupEodhG6VM_
1450167602877	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602878	Sync.Engine.History	WARN	Failed to reconcile incoming record FEYbTTakUf-r
1450167602879	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602880	Sync.Engine.History	WARN	Failed to reconcile incoming record 9GG7gzps_NT9
1450167602880	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602881	Sync.Engine.History	WARN	Failed to reconcile incoming record 8sQ7CMG82Wvn
1450167602882	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602882	Sync.Engine.History	WARN	Failed to reconcile incoming record 2ty6iJIrFyy0
1450167602883	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602884	Sync.Engine.History	WARN	Failed to reconcile incoming record 0Rz-MbOUxkBI
1450167602884	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602885	Sync.Engine.History	WARN	Failed to reconcile incoming record XPSEdfPRxYDH
1450167602886	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602887	Sync.Engine.History	WARN	Failed to reconcile incoming record oJI21lv2N-0V
1450167602887	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSyncCallback()@resource://services-common/async.js:101 < querySpinningly()@resource://services-common/async.js:201 < HistStore__findURLByGUID()@resource://gre/modules/services-sync/engines/history.js:165 < HistStore_itemExists()@resource://gre/modules/services-sync/engines/history.js:330 < SyncEngine.prototype._reconcile()@resource://services-sync/engines.js:1246 < SyncEngine.prototype._processIncoming/newitems.recordHandler()@resource://services-sync/engines.js:1084 < Collection.prototype.recordHandler/this._onProgress()@resource://services-sync/record.js:624 < Channel_onDataAvail()@resource://services-sync/resource.js:558 < <file:unknown>
1450167602888	Sync.Engine.History	WARN	Failed to reconcile incoming record NUi9_rU3O8-0
1450167602889	Sync.Engine.History	WARN	Encountered exception: [Exception... "App. Quitting"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "JS frame :: resource://services-common/async.js :: checkAppReady/onQuitApplication/Async.checkAppReady :: line 126"  data: no] Stack trace: checkAppReady/onQuitApplication/Async.checkAppReady()@resource://services-common/async.js:126 < waitForSync